### ISSUE TITLE
Support Node v6

### ISSUE THREAD

**Issue by msridhar** [Samsung/jalangi2#115]
Per #114, we should support Node v6.  Right now, we have a failing test case where `const` is used.  Also, I think we have some baked-in assumptions about the structure of the `node_modules` directory that will break down.  We should check all the standard use cases.

**Comment by liz425** [comment]
Though Jalangi2 currently not support ES6, is there any way to make Jalangi2 work with ES5 'strict mode'?

**Comment by msridhar** [comment]
This issue is about Node versions, not ES6. If there is an issue with strict mode please file it separately. Or if there's an extant issue you can comment there. Thanks!

**Comment by Muon** [comment]
The `const` problem is due to the instrumented code trying to use the value of `x` before it is declared. Though the name of `x` is still hoisted to the top of the function body, its value is not available until after the declaration. Attempts to use it will throw a `ReferenceError`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Temporal_dead_zone_and_errors_with_let for more information.
