### ISSUE TITLE
functionEnter after endExecution in setTimeout()

### ISSUE THREAD

**Issue by MaxSchlueter** [Samsung/jalangi2#128]
The function in setTimeout is called after the endExecution() callback.
Is this normal?

**Comment by jawline** [comment]
Unfortunately Jalangi2 generally calls endExecution after the main execution frame has completed (I.e. the script) rather than when all queued Asynchronous tasks are completed.

I worked around it in my project (Only works on Node) by adding a process.on('exit') handler in place of functionExit. This makes backtracking a hell of a lot harder though.

In general its a massive pain in the arse as there doesn't seem to be a standard mechanism to see what if any potential execution frames are queued and whether they will actually execute.

**Comment by msridhar** [comment]
Hrm, it seems that `direct.js` does invoke `endExecution()` in a handler for `'exit'`:

https://github.com/Samsung/jalangi2/blob/master/src/js/commands/direct.js#L68

But, `jalangi.js` is doing something different with a `finally` block:

https://github.com/Samsung/jalangi2/blob/master/src/js/commands/jalangi.js#L121

@MaxSchlueter are you using `jalangi.js`?  @ksen007 should we change `jalangi.js` to behave like `direct.js`?

**Comment by MaxSchlueter** [comment]
Yes, I'm using `jalangi.js`. What is the purpose of `direct.js`? Seems that I can't use it with the `--inlineIID` option...

If it is not changed, I would maybe clarify this in the documentation.

**Comment by msridhar** [comment]
`direct.js` can be used if you have scripts that are already instrumented on disk, whereas `jalangi.js` instruments the scripts as they are loaded.  I think we should change `jalangi.js` to work like `direct.js` for `endExecution()`.  I'll file a PR.
