### ISSUE TITLE
Feature Request: distinguish between ++ and +=1 in binary callback

### ISSUE THREAD

**Issue by JacksonGL** [Samsung/jalangi2#44]
In ```binaryPre``` and ```binary```, there seems to be no way to distinguish between the binary plus in  ```a.b++``` and the one in ```a.b+=1```. It may be useful to add another argument (e.g., ```isAuto```) to  ```binaryPre``` and ```binary``` callback.

**Comment by msridhar** [comment]
We have been adding features like these at a regular clip to jalangi2, and @ksen007 and I have noticed some significant additional overhead for analyses that don't need them (compared to using analysis2.js from Jalangi).  We need a better way to customize instrumentation to the needs of an analysis, so that analyses can get less overhead if needed.

**Comment by ksen007** [comment]
I am thinking about fixing that problem.
