### ISSUE TITLE
Please add a callback that triggers when entering a "finally" block.

### ISSUE THREAD

**Issue by johanneskloos** [Samsung/jalangi2#76]
Currently, there is no way to detect whether code is being executed in a "finally" block. Would it be possible to add a callback for when such a block is entered?

**Comment by ksen007** [comment]
We avoid to add any callback for any syntactic block structure because the goal of Jalangi 2 is to enable dynamic analysis without bloating the callback API.  There is a way to access the AST from a dynamic analysis  and you can use the AST to figure if a callback corresponds to the first callback from a finally block.
